### PR TITLE
Add build args for Next.js build

### PR DESCRIPTION
**Pull request by searsaw**
There were some missing build args that are used for building the Next.js app. I added those as args. I also moved the creation of the environment variables into a single layer since Docker will be able to cache them in one instead of making multiple.

### CODE REVIEW

**Review by krumware — APPROVED** [review]
LGTM

**Comment by krumware** [comment]
@searsaw can you please add the missing args to the docker-compose.yml as well?

Thanks for this!

**Review by krumware — CHANGES_REQUESTED** [review]
Docker-compose updates would be great as well

**Comment by searsaw** [comment]
@krumware I updated the `docker-compose.yaml` file.

**Review by krumware — APPROVED** [review]
tested and verified

**Pull request merged**
